on:
  workflow_dispatch:
jobs:
  create_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build
        run: |
          docker build . --tag ghcr.io/adalbertjnr/async_terraform:latest
          docker push ghcr.io/adalbertjnr/async_terraform:latest
